create table if not exists "user"
(
    id       integer generated by default as identity
    primary key,
    username varchar(30) not null,
    password varchar     not null,
    email    varchar     not null
    unique,
    role     varchar(30) not null
);

create table if not exists news_item
(
    id      integer generated by default as identity
    constraint news_pkey
    primary key,
    title   varchar(100) not null,
    author  varchar(30)  not null,
    date    date         not null,
    content varchar      not null
);

alter table "user"
    owner to postgres;


alter table news_item
    owner to postgres;


